apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
      - name: cont2
        image: teja7781/totalproject:replacetag
        ports:
          - containerPort: 8080
